name: GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # This will run daily at midnight (UTC)
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up GitHub Stats by DenverCoder1
        uses: DenverCoder1/github-readme-stats@v1  # Use v1 instead of v2
        with:
          username: zubair549
          theme: radical  # You can change the theme (e.g., dark, radical, etc.)
          hide_title: true # You can hide the title if you like
